from collections.abc import Hashable
from enum import IntEnum
from typing import Set, Optional, Callable, Tuple

import numpy as np


# class EntityState:
#     def __init__(self):
#         self.pos: Optional[np.ndarray] = None
#         self.vel: Optional[np.ndarray] = None
#
#         self.collisions: Optional[Set[Entity]] = None


# # Not yet sure why this should be a separate class
# class EntityAction:
#     pass

class Harm(IntEnum):
    NoHarm = 0
    MinorHarm = 1
    MajorHarm = 2


class HarmSource(IntEnum):
    NoHarmSource = 0
    Robot = 1
    Env = 2


# ENTITY #
class Entity:
    def __init__(
            self,
            name: Hashable,
            size: float,
            pos: Optional[np.ndarray] = None,
            movable: bool = False,
            collide: bool = False,
            actable: bool = False,
            density: float = 25.0,
            mass: float = 1.0,
            max_speed: Optional[float] = None
    ):
        self.name = name
        self.size = size

        self.movable = movable
        self.collide = collide
        self.actable = actable

        self.events = []

        # Init values - store in case they change and need to be reinit
        self._init_movable = movable
        self._init_collide = collide
        self._init_actable = actable
        self._init_pos = None if pos is None else pos.copy()

        self.density = density
        self.max_speed = max_speed
        self.mass = mass

        self.accel = None  # ?

        self.pos: Optional[np.ndarray] = pos
        self.vel: Optional[np.ndarray] = np.zeros(2, dtype=float)

        # Total force acting on entity along (x,y)
        self.force: Optional[np.ndarray] = np.zeros(2, dtype=float)
        # 'External' force acting on entity along (x,y)
        self.force_ext: Optional[np.ndarray] = np.zeros(2, dtype=float)
        # 'Internal' force acting on entity along (x,y) - force generated by agent
        self.force_int: Optional[np.ndarray] = np.zeros(2, dtype=float)

        self.collisions: Set[Tuple[Entity, str]] = set()
        # self.state = EntityState()

    def reset(self):
        self.movable = self._init_movable
        self.collide = self._init_collide
        self.actable = self._init_actable

        self.reset_force()

        self.collisions = set()

    def reset_force(self):
        self.force = np.zeros(2, dtype=float)
        self.force_ext = np.zeros(2, dtype=float)
        self.force_int = np.zeros(2, dtype=float)

    @staticmethod
    def force_magn(force: np.ndarray) -> float:
        return float(np.linalg.norm(force))

    def __hash__(self):
        return self.name

    def __repr__(self):
        class_name = self.__class__.__name__
        return f"{class_name} - name = {self.name}"

    @property
    def init_pos(self):
        return self._init_pos.copy() if self._init_pos is not None else None



class Landmark(Entity):
    def __init__(
            self,
            name: Hashable,
            size: float,
            pos: Optional[np.ndarray] = None
    ):
        super().__init__(
            name, size, pos=pos, movable=False, collide=False, actable=False
        )


class HarmableEntity(Entity):
    def __init__(
            self,
            name: Hashable,
            size: float,
            pos: Optional[np.ndarray] = None,
            movable: bool = False,
            collide: bool = False,
            actable: bool = False,
            # density: float = 25.0,
            mass: float = 1.0,
            max_speed: Optional[float] = None,
            minor_harm_threshold: float = 1.0,  # TODO: Get correct no
            major_harm_threshold: float = 2.0  # TODO: Get correct no
    ):
        super().__init__(
            name, size,
            pos=pos, movable=movable, collide=collide, actable=actable, mass=mass, max_speed=max_speed
        )

        self.minor_harm_threshold = minor_harm_threshold
        self.major_harm_threshold = major_harm_threshold

        self.current_harm = Harm.NoHarm
        self.harm_source: HarmSource = HarmSource.NoHarmSource

        self.is_harmable = True  # E.g. one reason is that it cannot be further harmed if current_harm = MajorHarm
        self.just_harmed = False

        self.is_harmed = False
        self.is_min_harmed = False
        self.is_maj_harmed = False
        self.is_min_env_harmed = False
        self.is_maj_env_harmed = False
        self.is_min_rob_harmed = False
        self.is_maj_rob_harmed = False

        # Force applied by env
        self.force_env: Optional[np.ndarray] = np.zeros(2, dtype=float)
        # Force applied by robot
        self.force_robot: Optional[np.ndarray] = np.zeros(2, dtype=float)

        # # 'External' force acting on entity along (x,y) - used for harm calc
        # self.force_ext: Optional[np.ndarray] = np.zeros(2, dtype=float)
        # # 'Internal' Force acting on entity along (x,y)
        # self.force_int: Optional[np.ndarray] = np.zeros(2, dtype=float)

    def set_harm(self, harm: Harm, harm_source: HarmSource):
        # Do nothing and return early if current_harm won't be changed
        if harm == self.current_harm:
            return

        if harm_source not in HarmSource.__members__.values():
            raise ValueError(f"Invalid value for harm_source={harm_source}. harm_source must satisfy harm_source in {HarmSource.__members__}")

        if harm == Harm.NoHarm:
            self.reset_harm()
        elif harm == Harm.MinorHarm:
            self.current_harm = harm
            self.harm_source = harm_source
            self.just_harmed = True

            self.is_harmed = True
            self.is_min_harmed = True
            # Assuming valid harm_source
            if harm_source == HarmSource.Env:
                self.is_min_env_harmed = True
            else:
                self.is_min_rob_harmed = True
        elif harm == Harm.MajorHarm:
            self.current_harm = harm
            self.harm_source = harm_source

            self.movable = False
            self.is_harmable = False
            self.actable = False

            self.just_harmed = True

            self.is_harmed = True
            self.is_maj_harmed = True
            if harm_source == HarmSource.Env:
                self.is_maj_env_harmed = True
            else:
                self.is_maj_rob_harmed = True
        else:
            raise ValueError(f"Invalid value for harm={harm}. harm must satisfy harm in {Harm.__members__}")



    ###############
    # -- RESET -- #
    ###############
    def reset_harm(self):
        self.current_harm = Harm.NoHarm
        self.harm_source = HarmSource.NoHarmSource

        self.is_harmed = False
        self.is_min_harmed = False
        self.is_maj_harmed = False
        self.is_min_env_harmed = False
        self.is_maj_env_harmed = False
        self.is_min_rob_harmed = False
        self.is_maj_rob_harmed = False

        self.is_harmable = True
        self.just_harmed = False

        self.movable = self._init_movable
        self.collide = self._init_collide
        self.actable = self._init_actable

    def reset_force(self):
        super().reset_force()
        self.force_env = np.zeros(2, dtype=float)
        self.force_robot = np.zeros(2, dtype=float)
    ###############


class AgentEntity(HarmableEntity):
    def __init__(
            self,
            name: Hashable,
            size: float,
            pos: Optional[np.ndarray] = None,
            movable: bool = False,
            collide: bool = True,
            mass: float = 1.0,
            max_speed: Optional[float] = None,
            speediness: float = 1.0,  # Modifier to control signal impacting speed of agent,
            speediness_harm_mod = 0.5,  # Modifier on speediness when minorly harmed
            minor_harm_threshold: float = 1.0,  # TODO: Get correct no
            major_harm_threshold: float = 2.0  # TODO: Get correct no
    ):
        super().__init__(
            name, size,
            pos=pos,
            movable=movable, collide=collide, actable=True,
            mass=mass, max_speed=max_speed,
            minor_harm_threshold=minor_harm_threshold, major_harm_threshold=major_harm_threshold
        )

        # Action is an (x, y) control signal
        self.action: Optional[np.ndarray] = None

        if speediness <= 0:
            raise ValueError(f"Invalid value for speediness={speediness}. speediness must satisfy speediness>0")

        self.speediness: float = speediness
        self._init_speediness = speediness

        if not 0 <= speediness_harm_mod <= 1:
            raise ValueError(f"Invalid value for speediness_harm_mod={speediness_harm_mod}. "
                             f"speediness_harm_mod must satisfy 0<=speediness_harm_mod<=1")
        self.speediness_harm_mod = speediness_harm_mod


        # self.minor_harm_threshold = minor_harm_threshold
        # self.major_harm_threshold = major_harm_threshold
        #
        # self.current_harm = Harm.NoHarm

        self.is_terminated = False

    def reset_harm(self):
        super().reset_harm()
        self.speediness = self._init_speediness

    def set_harm(self, harm: Harm, harm_source: HarmSource):
        if harm != self.current_harm:
            super().set_harm(harm, harm_source)

            # Augment speed if minorly harmed
            if harm == Harm.MinorHarm:
                self.speediness = self.speediness * self.speediness_harm_mod

    # def calc_control_force(self) -> np.ndarray:
    #     # return
    #     raise NotImplementedError


class Hazard(Entity):
    def __init__(
            self,
            name: Hashable,
            size: float,
            hazard_type: str,
            pos: Optional[np.ndarray] = None
    ):
        self.hazard_type = hazard_type

        if hazard_type == "lava":
            self.is_fatal = True
        elif hazard_type == "pillar":
            self.is_fatal = False
        else:
            raise ValueError(f"Invalid value for hazard_type={hazard_type}")

        collide = not self.is_fatal

        super().__init__(name, size, pos=pos, movable=False, collide=collide, actable=False)


class Decoration(HarmableEntity):
    def __init__(
            self,
            name: Hashable,
            size: float,
            pos: Optional[np.ndarray] = None,
            minor_harm_threshold: float = 1.0,  # TODO: Get correct no
            major_harm_threshold: float = 2.0  # TODO: Get correct no
    ):
        super().__init__(
            name, size,
            pos=pos, movable=False, collide=True, actable=False,
            minor_harm_threshold=minor_harm_threshold, major_harm_threshold=major_harm_threshold
        )


# class Robot(Entity):
#     pass
#
#
# class AgentRobot(Robot):
#     pass
#
#
# class EvilRobot(Robot):
#     pass
#
#
# class Human(Entity):
#     pass


# class ForceSource(IntEnum):
#     NoForceSource = 0
#     Robot = 1
#     Env = 2

